//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        public int ID_BOLETA { get; set; }
        public System.DateTime FECHA_BOLETA { get; set; }
        public int NETO_BOLETA { get; set; }
        public int IVA_BOLETA { get; set; }
        public int TOTAL_BOLETA { get; set; }
        public decimal ID_COMPRA { get; set; }
        public string RUT_CLIENTE { get; set; }
        public short ID_MEDIO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual MEDIO_PAGO MEDIO_PAGO { get; set; }
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
    }
}
