//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.DIRECCION = new HashSet<DIRECCION>();
            this.EMPRESA = new HashSet<EMPRESA>();
        }
    
        public string RUT_CLIENTE { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public short ID_USUARIO { get; set; }
        public string CORREO_CLIENTE { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<DIRECCION> DIRECCION { get; set; }
        public virtual ICollection<EMPRESA> EMPRESA { get; set; }
    }
}
