//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESPACHO
    {
        public int ID_DESPACHO { get; set; }
        public decimal ID_DETALLE { get; set; }
        public short ID_ESTADO { get; set; }
        public string RUT_EMPLEADO { get; set; }
        public System.DateTime FECHA_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_RECEPCION { get; set; }
    
        public virtual DETALLE_ORDEN DETALLE_ORDEN { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ESTADO_DESPACHO ESTADO_DESPACHO { get; set; }
    }
}
