//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ORDEN
    {
        public DETALLE_ORDEN()
        {
            this.DESPACHO = new HashSet<DESPACHO>();
        }
    
        public decimal ID_DETALLE { get; set; }
        public long ID_PRODUCTO { get; set; }
        public short CANTIDAD { get; set; }
        public decimal ID_COMPRA { get; set; }
    
        public virtual ICollection<DESPACHO> DESPACHO { get; set; }
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
