//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECCION
    {
        public int ID_DIRECCION { get; set; }
        public string DIRECCION1 { get; set; }
        public short ID_COMUNA { get; set; }
        public string RUT_CLIENTE { get; set; }
        public Nullable<short> ID_EMPRESA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
