//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.DIRECCION = new HashSet<DIRECCION>();
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public short ID_EMPRESA { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string RUT_EMPRESA { get; set; }
        public short ID_TIPO { get; set; }
        public string CORREO_EMPRESA { get; set; }
        public string RUT_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DIRECCION> DIRECCION { get; set; }
        public virtual TIPO_EMPRESA TIPO_EMPRESA { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
    }
}
