//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_COMPRA
    {
        public ESTADO_COMPRA()
        {
            this.COMPRA_PROVEEDOR = new HashSet<COMPRA_PROVEEDOR>();
        }
    
        public int ID_ESTADO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<COMPRA_PROVEEDOR> COMPRA_PROVEEDOR { get; set; }
    }
}
