//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int ID_FACTURA { get; set; }
        public System.DateTime FECHA_FACTURA { get; set; }
        public int NETO_FACTURA { get; set; }
        public int IVA_FACTURA { get; set; }
        public int TOTAL_FACTURA { get; set; }
        public decimal ID_COMPRA { get; set; }
        public short ID_EMPRESA { get; set; }
        public short ID_MEDIO { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual MEDIO_PAGO MEDIO_PAGO { get; set; }
        public virtual ORDEN_COMPRA ORDEN_COMPRA { get; set; }
    }
}
