//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FerreteriaFermeEntities : DbContext
    {
        public FerreteriaFermeEntities()
            : base("name=FerreteriaFermeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOLETA> BOLETA { get; set; }
        public DbSet<CARGO> CARGO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COMPRA_PROVEEDOR> COMPRA_PROVEEDOR { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<COSTO_ENVIO> COSTO_ENVIO { get; set; }
        public DbSet<DESPACHO> DESPACHO { get; set; }
        public DbSet<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
        public DbSet<DIRECCION> DIRECCION { get; set; }
        public DbSet<EMPLEADO> EMPLEADO { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<ESTADO_COMPRA> ESTADO_COMPRA { get; set; }
        public DbSet<ESTADO_DESPACHO> ESTADO_DESPACHO { get; set; }
        public DbSet<ESTADO_RECEPCION> ESTADO_RECEPCION { get; set; }
        public DbSet<ESTADO_USUARIO> ESTADO_USUARIO { get; set; }
        public DbSet<FACTURA> FACTURA { get; set; }
        public DbSet<FAMILIA_PRODUCTO> FAMILIA_PRODUCTO { get; set; }
        public DbSet<MEDIO_PAGO> MEDIO_PAGO { get; set; }
        public DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PRODUCTO_PROVEEDOR> PRODUCTO_PROVEEDOR { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECEPCION_PRODUCTO> RECEPCION_PRODUCTO { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<RESUMEN_PRODUCTOS> RESUMEN_PRODUCTOS { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<TIPO_COMPRA> TIPO_COMPRA { get; set; }
        public DbSet<TIPO_EMPRESA> TIPO_EMPRESA { get; set; }
        public DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
