//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_COMPRA
    {
        public ORDEN_COMPRA()
        {
            this.BOLETA = new HashSet<BOLETA>();
            this.DETALLE_ORDEN = new HashSet<DETALLE_ORDEN>();
            this.FACTURA = new HashSet<FACTURA>();
            this.RECEPCION_PRODUCTO = new HashSet<RECEPCION_PRODUCTO>();
        }
    
        public decimal ID_COMPRA { get; set; }
        public System.DateTime FECHA_ORDEN { get; set; }
        public Nullable<short> DESCUENTO { get; set; }
        public string RUT_EMPLEADO { get; set; }
        public short ID_TIPOCOM { get; set; }
        public short ID_COSTOENVIO { get; set; }
    
        public virtual ICollection<BOLETA> BOLETA { get; set; }
        public virtual COSTO_ENVIO COSTO_ENVIO { get; set; }
        public virtual ICollection<DETALLE_ORDEN> DETALLE_ORDEN { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual TIPO_COMPRA TIPO_COMPRA { get; set; }
        public virtual ICollection<RECEPCION_PRODUCTO> RECEPCION_PRODUCTO { get; set; }
    }
}
