//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PROVEEDOR
    {
        public int ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public short CANTIDAD { get; set; }
        public int PRECIO_UNITARIO { get; set; }
        public int ID_COMPRA { get; set; }
    
        public virtual COMPRA_PROVEEDOR COMPRA_PROVEEDOR { get; set; }
    }
}
