//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.COMPRA_PROVEEDOR = new HashSet<COMPRA_PROVEEDOR>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
            this.RUBRO = new HashSet<RUBRO>();
        }
    
        public short ID_PROVEEDOR { get; set; }
        public string NOMBRE_PROVEEDOR { get; set; }
        public string RUT_PROVEEDOR { get; set; }
        public long CELULAR { get; set; }
        public string CORREO { get; set; }
    
        public virtual ICollection<COMPRA_PROVEEDOR> COMPRA_PROVEEDOR { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        public virtual ICollection<RUBRO> RUBRO { get; set; }
    }
}
