//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESUMEN_PRODUCTOS
    {
        public int ID_RESPRO { get; set; }
        public int MES_ANNO { get; set; }
        public long ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public string TIPO_PRODUCTO { get; set; }
        public string FAMILIA_PRODUCTO { get; set; }
        public short CANTIDAD { get; set; }
    }
}
