//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaFerme.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_EMPRESA
    {
        public TIPO_EMPRESA()
        {
            this.EMPRESA = new HashSet<EMPRESA>();
        }
    
        public short ID_TIPO { get; set; }
        public string NOMBRE_TIPO { get; set; }
    
        public virtual ICollection<EMPRESA> EMPRESA { get; set; }
    }
}
